INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (1, 'goal.private-discord-agent-workspace', 'goal', 'Operate coding agents from a private Discord workspace', 'Use Discord as a familiar, mobile, conversational surface for initiating and supervising local coding work without treating Discord itself as the execution system.', 'active', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"active","kind":"goal","arc":"origin","evidence":["path:README.md@1835066c7c31ca327384fe217b7bffd960128a21","upstream:NicolaiLolansen/DiscordClaude README.md"],"views":["overview","transport-interaction","current-architecture"],"current":true,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"goal.private-discord-agent-workspace"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (2, 'option.discord-conversational-surface', 'option', 'Choose Discord as the remote interaction surface', 'Discord supplied private-server access, bot identity, channels, threads, buttons, polls, notifications, and access from phone or desktop, making it a practical operator surface for local agents.', 'completed', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"active","kind":"alternative","arc":"origin","evidence":["upstream:NicolaiLolansen/DiscordClaude README.md","path:README.md@1835066c7c31ca327384fe217b7bffd960128a21"],"views":["overview","transport-interaction"],"current":true,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"option.discord-conversational-surface"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (3, 'action.import-discordclaude-poc', 'action', 'Derive the repository from DiscordClaude', 'The initial codebase preserved the DiscordClaude model: one Discord bot process, project channels, a thread per prompt, Claude Agent SDK execution, resumable sessions, tool visibility, approvals, recurring loops, and completion pings.', 'completed', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"proof-of-concept","kind":"implementation","arc":"discordclaude-poc","evidence":["upstream:NicolaiLolansen/DiscordClaude README.md","path:README.md@1835066c7c31ca327384fe217b7bffd960128a21"],"views":["overview","transport-interaction","primary-subagents"],"current":false,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"action.import-discordclaude-poc"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (4, 'outcome.poc-proved-remote-agent-control', 'outcome', 'DiscordClaude proved remote conversational control', 'The proof of concept established that Discord could ingest prompts, stream local Claude activity into threads, resume provider sessions, collect approvals, and notify the operator from a private server.', 'completed', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"proof-of-concept","kind":"outcome","arc":"discordclaude-poc","evidence":["upstream:NicolaiLolansen/DiscordClaude README.md"],"views":["overview","transport-interaction","testing"],"current":false,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"outcome.poc-proved-remote-agent-control"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (5, 'observation.poc-did-not-prove-general-runtime', 'observation', 'The proof of concept did not establish a general runtime', 'Claude-specific services, project JSON, Discord-thread session ownership, and a single bot process demonstrated product value but did not prove provider neutrality, durable execution authority, exact-once delivery, offline verification, or safe restart recovery.', 'completed', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"active","kind":"observation","arc":"discordclaude-poc","evidence":["upstream:NicolaiLolansen/DiscordClaude README.md","PR:#1 merged b775839547c3c5df9e689e212cd565b4353262d7"],"views":["overview","current-architecture","reliability-risk"],"current":false,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"observation.poc-did-not-prove-general-runtime"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (6, 'option.discord-history-as-canonical-state', 'option', 'Use Discord history as the complete conversation store', 'A channel or thread could have been treated as the transcript and session authority, but message history cannot transactionally bind provider sessions, worktrees, task results, replay protection, memory provenance, or restart state.', 'rejected', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"rejected","kind":"alternative","arc":"conversation-identity","evidence":["PR:#1 merged b775839547c3c5df9e689e212cd565b4353262d7","path:docs/explanation/architecture/provider-neutral-runtime.md@c36f1324787039df31ec86d63aac44904eebe28b"],"views":["conversation-identity","reliability-risk"],"current":false,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"option.discord-history-as-canonical-state"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (7, 'revisit.claude-specific-coupling', 'revisit', 'Revisit Claude-specific bot coupling', 'Adding Codex and later OpenCode required provider behavior, Discord rendering, task state, and session identity to stop depending on Claude SDK types and conventions.', 'completed', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"active","kind":"correction","arc":"provider-neutrality","evidence":["PR:#1 merged b775839547c3c5df9e689e212cd565b4353262d7","PR:#8 merged 94c3324c547d23e450d420b1288a6c165a272165"],"views":["overview","current-architecture","transport-interaction"],"current":false,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"revisit.claude-specific-coupling"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (8, 'decision.provider-neutral-contracts', 'decision', 'Normalize providers behind agent contracts', 'Discord and coordination code depend on AgentProvider, AgentEvent, TaskResult, and provider registry contracts; each SDK or protocol remains confined to an adapter.', 'active', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"active","kind":"decision","arc":"provider-neutrality","evidence":["PR:#2 merged 2862109e4a7b315b281ecdb0a42bb17421a1b5f6","path:docs/explanation/architecture/provider-neutral-runtime.md@c36f1324787039df31ec86d63aac44904eebe28b"],"views":["overview","current-architecture","transport-interaction"],"current":true,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"decision.provider-neutral-contracts"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (9, 'action.provider-neutral-foundation', 'action', 'Build the provider-neutral persistence and rendering foundation', 'PRs 2 and 4 added SQLite repositories, guarded worktrees, normalized rendering, TaskCoordinator, early session persistence, recovery notifications, centralized redaction, and removal of obsolete Claude-only compatibility layers.', 'completed', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"active","kind":"implementation","arc":"provider-neutrality","evidence":["PR:#2 head cfb83707e2f837d7e25c0d9107c2323a2665002c merged 2862109e4a7b315b281ecdb0a42bb17421a1b5f6","PR:#4 head 7bd4be6bc131ff3e5bc69efee70c2f80b368b2f9 merged df46057dc6dd43e172d1be6cc458101d8d428bbb"],"views":["overview","current-architecture","testing"],"current":false,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"action.provider-neutral-foundation"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (10, 'action.add-codex-provider', 'action', 'Add Codex App Server and PM support', 'Codex was integrated through a local App Server transport with normalized events, authentication, approvals, questions, cancellation, usage, recovery, and a bounded primary-agent model.', 'completed', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"active","kind":"implementation","arc":"provider-neutrality","evidence":["PR:#8 head 9cf0068a709785ce06bf5ff80f11cc63091c87a1 merged 94c3324c547d23e450d420b1288a6c165a272165","path:docs/explanation/architecture/provider-neutral-runtime.md@c36f1324787039df31ec86d63aac44904eebe28b"],"views":["current-architecture","testing"],"current":false,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"action.add-codex-provider"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (11, 'action.add-opencode-provider', 'action', 'Add OpenCode through ACP', 'OpenCode became a third project-task provider through ACP and later gained a deny-all primary model, proving that the abstraction could span different transports without claiming every provider behavior was identical.', 'completed', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"active","kind":"implementation","arc":"provider-neutrality","evidence":["PR:#13 merged","PR:#15 merged","path:package.json@1835066c7c31ca327384fe217b7bffd960128a21"],"views":["current-architecture","testing"],"current":false,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"action.add-opencode-provider"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (12, 'outcome.provider-neutral-but-adapters-specific', 'outcome', 'Multi-provider orchestration is implemented, not provider sameness', 'Claude, Codex, and OpenCode share lifecycle contracts, persistence, and Discord presentation, while authentication, session protocols, approval mechanics, model selection, and failure modes remain provider-specific.', 'active', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"active","kind":"outcome","arc":"provider-neutrality","evidence":["path:docs/explanation/architecture/provider-neutral-runtime.md@c36f1324787039df31ec86d63aac44904eebe28b","path:package.json@1835066c7c31ca327384fe217b7bffd960128a21"],"views":["overview","current-architecture"],"current":true,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"outcome.provider-neutral-but-adapters-specific"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (13, 'decision.primary-pm-agent', 'decision', 'Keep one persistent primary PM-style agent', 'The primary agent owns conversational planning, bounded memory, summaries, task proposals, and decision collection, but not repository tools or direct task lifecycle mutation.', 'active', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"active","kind":"decision","arc":"primary-subagents","evidence":["PR:#1 merged b775839547c3c5df9e689e212cd565b4353262d7","PR:#8 merged 94c3324c547d23e450d420b1288a6c165a272165","path:docs/explanation/architecture/primary-agent-boundary.md@35392a9504e4b9f590b25140538aaff0e92636d3"],"views":["overview","primary-subagents","authority-security","current-architecture"],"current":true,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"decision.primary-pm-agent"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (14, 'decision.primary-tool-isolation', 'decision', 'Separate planning authority from coding tools', 'Provider-specific primary models are configured with no tools or read-only network-disabled turns so conversation cannot silently become an unbounded coding session.', 'active', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"active","kind":"security-boundary","arc":"primary-subagents","evidence":["path:docs/explanation/architecture/primary-agent-boundary.md@35392a9504e4b9f590b25140538aaff0e92636d3"],"views":["primary-subagents","authority-security","current-architecture"],"current":true,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"decision.primary-tool-isolation"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (15, 'option.flat-subagent-messages', 'option', 'Represent subagent work as flat channel messages', 'Flat messages would intermingle unrelated tasks, approvals, continuations, and completion notices, and would not provide a stable surface for a provider-fixed task context.', 'rejected', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"rejected","kind":"alternative","arc":"primary-subagents","evidence":["PR:#1 merged b775839547c3c5df9e689e212cd565b4353262d7","upstream:NicolaiLolansen/DiscordClaude README.md"],"views":["primary-subagents","transport-interaction"],"current":false,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"option.flat-subagent-messages"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (16, 'decision.task-threads-as-interaction-surfaces', 'decision', 'Use Discord threads as task interaction surfaces', 'A task thread gives each delegated or directly initiated task a focused visible transcript and continuation route while preserving one bot identity and one primary planning channel.', 'active', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"active","kind":"decision","arc":"primary-subagents","evidence":["PR:#1 merged b775839547c3c5df9e689e212cd565b4353262d7","PR:#8 merged 94c3324c547d23e450d420b1288a6c165a272165","path:docs/explanation/architecture/provider-neutral-runtime.md@c36f1324787039df31ec86d63aac44904eebe28b"],"views":["primary-subagents","transport-interaction","current-architecture"],"current":true,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"decision.task-threads-as-interaction-surfaces"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (17, 'decision.provider-fixed-task-sessions', 'decision', 'Bind each durable task to one provider session', 'A durable task keeps an immutable provider identity, session, branch, and worktree. Switching provider creates a confirmed sibling handoff rather than mutating the original thread into a different execution context.', 'active', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"active","kind":"decision","arc":"primary-subagents","evidence":["PR:#8 merged 94c3324c547d23e450d420b1288a6c165a272165","path:docs/explanation/architecture/provider-neutral-runtime.md@c36f1324787039df31ec86d63aac44904eebe28b"],"views":["primary-subagents","conversation-identity","current-architecture"],"current":true,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"decision.provider-fixed-task-sessions"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (18, 'observation.thread-is-not-execution', 'observation', 'A Discord thread is not a subagent execution record', 'The thread is a transport and presentation address. SQLite task, provider-session, event, result, worktree, and external-runtime bindings carry the durable identities and state.', 'active', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"active","kind":"distinction","arc":"primary-subagents","evidence":["path:docs/explanation/architecture/provider-neutral-runtime.md@c36f1324787039df31ec86d63aac44904eebe28b","path:docs/explanation/architecture/factory-floor-activity-boundary.md@4511942771e23f529d7cfe7400e5bde92829c452"],"views":["primary-subagents","conversation-identity","factory-floor","current-architecture"],"current":true,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"observation.thread-is-not-execution"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (19, 'action.thread-delete-cleanup', 'action', 'Make thread deletion an idempotent cleanup signal', 'Deleting a thread can cancel the associated direct task and terminalize a scheduled loop, but cleanup remains independent and preserves the worktree rather than pretending the Discord deletion erased execution history.', 'completed', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"active","kind":"implementation","arc":"primary-subagents","evidence":["test:src/handlers/threadDeleteHandler.test.ts current main","CI:1599c42501e5fa7bd8d10c00dc687910b1055b2e"],"views":["primary-subagents","reliability-risk"],"current":false,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"action.thread-delete-cleanup"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (20, 'decision.discord-operator-interface', 'decision', 'Use Discord for conversational operator control', 'Discord handles task initiation, progress visibility, questions, approvals, lightweight notifications, project channels, and human-in-the-loop coordination.', 'active', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"active","kind":"decision","arc":"operator-interface","evidence":["path:README.md@1835066c7c31ca327384fe217b7bffd960128a21","path:docs/explanation/architecture/provider-neutral-runtime.md@c36f1324787039df31ec86d63aac44904eebe28b"],"views":["overview","transport-interaction","current-architecture"],"current":true,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"decision.discord-operator-interface"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (21, 'observation.discord-not-authoritative-runtime', 'observation', 'Discord is unsuitable as authoritative execution state', 'Gateway events, messages, components, and threads are externally delivered projections with rate limits and partial failure. They cannot replace a transactional queue, task ledger, execution attempts, artifact lineage, approvals, receipts, or recovery state.', 'active', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"active","kind":"boundary","arc":"operator-interface","evidence":["PR:#14 merged d55ef6c8d5efe6ce19b60503766287bd7548a66f","path:docs/explanation/architecture/factory-floor-activity-boundary.md@4511942771e23f529d7cfe7400e5bde92829c452"],"views":["overview","transport-interaction","factory-floor","reliability-risk"],"current":true,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"observation.discord-not-authoritative-runtime"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (22, 'decision.structured-decisions', 'decision', 'Use bounded structured controls for operator decisions', 'Buttons, selects, and polls reduce ambiguity for approvals, prioritization, branching, and multiple-choice questions, while every result returns through a conversation or task decision path.', 'active', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"active","kind":"decision","arc":"structured-interaction","evidence":["PR:#8 merged 94c3324c547d23e450d420b1288a6c165a272165","path:src/primary/primaryConversationService.ts@89cb32716997e698a0d3e1d745d429190a22846e"],"views":["transport-interaction","primary-subagents","repl"],"current":true,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"decision.structured-decisions"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (23, 'observation.polls-are-not-universal-ledgers', 'observation', 'Polls are useful inputs, not universal approval ledgers', 'Discord polls are asynchronous platform objects with timeout, replay, participant, and result-collection concerns. The REPL therefore maps poll-shaped choices to synchronous selection, and sensitive external runtime mutations require canonical state plus fresh authority checks.', 'active', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"active","kind":"qualification","arc":"structured-interaction","evidence":["PR:#24 merged 3f05ed5b39899bfc19ac63968f30842bccd357c6","path:docs/how-to/operations/use-the-terminal-repl.md@7a091f17fb79b2a33929b4ae008c7cfef47ea2d0","path:docs/explanation/architecture/factory-floor-activity-boundary.md@4511942771e23f529d7cfe7400e5bde92829c452"],"views":["transport-interaction","repl","authority-security"],"current":false,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"observation.polls-are-not-universal-ledgers"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (24, 'decision.quiet-structured-notifications', 'decision', 'Prefer quiet structured status over message volume', 'The operator experience uses typing signals, coalesced or edited control cards, bounded text fallbacks, completion/failure summaries, and targeted questions instead of treating frequent messages as proof of progress.', 'active', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"active","kind":"decision","arc":"notifications","evidence":["PR:#16 merged","PR:#20 merged","PR:#26 merged","test:src/discord/taskRenderer.test.ts current main"],"views":["transport-interaction","reliability-risk","current-architecture"],"current":true,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"decision.quiet-structured-notifications"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (25, 'outcome.notifications-are-projections', 'outcome', 'Notifications remain projections rather than durable receipts', 'A successful stored terminal result remains successful even when its Discord render fails. Discord delivery can be retried or degraded without rewriting the task outcome.', 'active', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"active","kind":"outcome","arc":"notifications","evidence":["test:src/coordinator/taskCoordinator.test.ts current main","test:src/discord/taskRenderer.test.ts current main","CI:1599c42501e5fa7bd8d10c00dc687910b1055b2e"],"views":["transport-interaction","reliability-risk","current-architecture"],"current":true,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"outcome.notifications-are-projections"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (26, 'observation.discord-platform-constraints', 'observation', 'Discord imposes delivery, size, permission, and interaction constraints', 'Message limits, component deadlines, thread and permission capabilities, gateway reconnects, burst traffic, stale message objects, embed rejection, and duplicate or out-of-order delivery shape the adapter design.', 'active', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"active","kind":"platform-constraint","arc":"discord-constraints","evidence":["upstream:NicolaiLolansen/DiscordClaude README.md","test:src/discord/taskRenderer.test.ts current main","path:.github/workflows/ci.yml@aee82c9e42e1495fee67347741e143fb29880491"],"views":["transport-interaction","reliability-risk"],"current":false,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"observation.discord-platform-constraints"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (27, 'action.capability-aware-delivery', 'action', 'Add capability checks and bounded presentation fallbacks', 'Discord Agent evaluates permissions, suppresses mentions, caps or chunks output, retries once after embed rejection, falls back to plain text, refetches stale control cards, and keeps update queues recoverable.', 'completed', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"active","kind":"implementation","arc":"discord-constraints","evidence":["PR:#53 merged","test:src/discord/taskRenderer.test.ts current main","test:src/discord/presentationDelivery.test.ts current main"],"views":["transport-interaction","reliability-risk","current-architecture"],"current":true,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"action.capability-aware-delivery"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (28, 'observation.gateway-exactly-once-unverified', 'observation', 'Gateway exact-once and in-order delivery remain unproven', 'Deterministic tests cover handlers and retry behavior, but they do not prove production gateway ordering, reconnect delivery, interaction timing, or every Discord-side rate-limit regime.', 'active', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"unresolved","kind":"risk","arc":"discord-constraints","evidence":["CI:1599c42501e5fa7bd8d10c00dc687910b1055b2e 122 Vitest files 817 tests","path:package.json@1835066c7c31ca327384fe217b7bffd960128a21 smoke:discord"],"views":["testing","reliability-risk"],"current":false,"owner_repo":"laurajoyhutchins/discordagent","confidence":"unresolved","semantic_id":"observation.gateway-exactly-once-unverified"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (29, 'decision.sqlite-durable-state', 'decision', 'Own durable direct-runtime state in SQLite', 'Projects, messages, memories, tasks, worktrees, provider sessions, normalized events, results, settings, loops, and adapter bindings survive beyond Discord message objects and provider process memory.', 'active', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"active","kind":"decision","arc":"conversation-identity","evidence":["PR:#2 merged 2862109e4a7b315b281ecdb0a42bb17421a1b5f6","PR:#4 merged df46057dc6dd43e172d1be6cc458101d8d428bbb","path:docs/explanation/architecture/provider-neutral-runtime.md@c36f1324787039df31ec86d63aac44904eebe28b"],"views":["conversation-identity","current-architecture","reliability-risk"],"current":true,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"decision.sqlite-durable-state"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (30, 'decision.internal-conversation-id', 'decision', 'Separate internal conversation identity from Discord message identity', 'PrimaryConversationService receives a stable conversationId and writes repository-owned message IDs. Discord channel IDs and the terminal identifier select transcripts; individual Discord message IDs remain evidence and routing references rather than the conversation key.', 'active', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"active","kind":"decision","arc":"conversation-identity","evidence":["path:src/primary/primaryConversationService.ts@89cb32716997e698a0d3e1d745d429190a22846e","path:docs/how-to/operations/use-the-terminal-repl.md@7a091f17fb79b2a33929b4ae008c7cfef47ea2d0"],"views":["conversation-identity","repl","current-architecture"],"current":true,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"decision.internal-conversation-id"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (31, 'decision.provider-session-separate', 'decision', 'Keep provider session identity separate from repository conversation state', 'Provider session identifiers resume provider work, but journal, retrieval, memory, task identity, and operator transcript belong to Discord Agent. A changed provider-session identity during continuation is a failure.', 'active', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"active","kind":"decision","arc":"conversation-identity","evidence":["path:docs/explanation/architecture/provider-neutral-runtime.md@c36f1324787039df31ec86d63aac44904eebe28b","path:docs/explanation/architecture/primary-agent-boundary.md@35392a9504e4b9f590b25140538aaff0e92636d3"],"views":["conversation-identity","primary-subagents","current-architecture"],"current":true,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"decision.provider-session-separate"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (32, 'action.restart-recovery-without-replay', 'action', 'Recover interrupted state without automatic task replay', 'Startup restores repositories and marks or reports interrupted work, but does not silently replay a provider turn or claim exactly-once execution after a crash.', 'completed', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"active","kind":"correction","arc":"conversation-identity","evidence":["PR:#4 merged df46057dc6dd43e172d1be6cc458101d8d428bbb","test:src/services/runtimeRestoreStartup.test.ts current main"],"views":["conversation-identity","reliability-risk","current-architecture"],"current":true,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"action.restart-recovery-without-replay"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (33, 'observation.restart-is-not-exactly-once', 'observation', 'Restart recovery is not exact-once execution', 'Durable records, idempotent migrations, and explicit recovery actions reduce ambiguity, but provider side effects may have occurred before a crash and cannot be inferred solely from Discord or local restart state.', 'active', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"unresolved","kind":"risk","arc":"conversation-identity","evidence":["PR:#4 merged df46057dc6dd43e172d1be6cc458101d8d428bbb","test:src/services/runtimeRestoreStartup.test.ts current main"],"views":["conversation-identity","reliability-risk"],"current":false,"owner_repo":"laurajoyhutchins/discordagent","confidence":"qualified","semantic_id":"observation.restart-is-not-exactly-once"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (34, 'observation.discord-coupling-hindered-development', 'observation', 'A live Discord dependency hindered local debugging and verification', 'Before the REPL and headless mode, exercising the primary conversation path required bot login, a private server, channel resolution, and gateway behavior even when the code under test was transport-neutral.', 'completed', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"active","kind":"problem","arc":"repl","evidence":["PR:#24 merged 3f05ed5b39899bfc19ac63968f30842bccd357c6","PR:#27 merged 015aa5062735bf1233b400ee13e453029887c1ec"],"views":["repl","testing"],"current":false,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"observation.discord-coupling-hindered-development"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (35, 'decision.transport-neutral-primary-conversation', 'decision', 'Extract a transport-neutral primary conversation service', 'PrimaryConversationService owns journaling, context assembly, model response, memory writes, task proposals, and decision continuation without importing Discord or terminal types.', 'active', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"active","kind":"decision","arc":"repl","evidence":["PR:#24 head ac4f6c28dadd435d2c78c7c36d24cbc01b8040da merged 3f05ed5b39899bfc19ac63968f30842bccd357c6","path:src/primary/primaryConversationService.ts@89cb32716997e698a0d3e1d745d429190a22846e"],"views":["repl","current-architecture","conversation-identity"],"current":true,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"decision.transport-neutral-primary-conversation"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (36, 'action.terminal-repl', 'action', 'Add the local terminal REPL adapter', 'The REPL reads stdin, writes stdout, uses terminal:primary, supports project/provider/model/task commands, renders numbered decisions, serializes turns, distinguishes /exit from SIGINT, and shares the production conversation service.', 'completed', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"active","kind":"implementation","arc":"repl","evidence":["PR:#24 merged 3f05ed5b39899bfc19ac63968f30842bccd357c6","path:docs/how-to/operations/use-the-terminal-repl.md@7a091f17fb79b2a33929b4ae008c7cfef47ea2d0","test:src/terminal/repl.test.ts 32 tests current main"],"views":["overview","repl","testing","current-architecture"],"current":true,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"action.terminal-repl"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (37, 'outcome.repl-supported-harness-not-discord-equivalent', 'outcome', 'The REPL is supported but not equivalent to live Discord', 'It is both a usable primary-agent interface and a developer harness. It does not validate gateway delivery, Discord permissions, native asynchronous polls, thread creation, or Discord rendering behavior.', 'active', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"active","kind":"qualification","arc":"repl","evidence":["path:docs/how-to/operations/use-the-terminal-repl.md@7a091f17fb79b2a33929b4ae008c7cfef47ea2d0","PR:#27 merged 015aa5062735bf1233b400ee13e453029887c1ec"],"views":["repl","testing","reliability-risk"],"current":true,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"outcome.repl-supported-harness-not-discord-equivalent"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (38, 'decision.deterministic-offline-tests', 'decision', 'Make core behavior verifiable without live Discord', 'Discord events, provider transports, repositories, renderers, lifecycle races, authorization, and recovery are exercised with deterministic tests and injected fakes; live credentials remain outside default CI.', 'active', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"active","kind":"decision","arc":"testing","evidence":["path:.github/workflows/ci.yml@aee82c9e42e1495fee67347741e143fb29880491","PR:#27 merged 015aa5062735bf1233b400ee13e453029887c1ec"],"views":["testing","current-architecture"],"current":true,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"decision.deterministic-offline-tests"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (39, 'action.headless-agent-smoke', 'action', 'Add an opt-in headless live-provider smoke path', 'The smoke path initializes production repositories, providers, coordinator, primary model, conversation service, and shutdown without fetching Discord channels; delegated thread launch and Discord recovery rendering are disabled.', 'completed', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"active","kind":"implementation","arc":"testing","evidence":["PR:#27 head 652945b22a0966049099143791d9c2fc6fe7efd3 merged 015aa5062735bf1233b400ee13e453029887c1ec","path:package.json@1835066c7c31ca327384fe217b7bffd960128a21 smoke:agent"],"views":["testing","repl","current-architecture"],"current":true,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"action.headless-agent-smoke"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (40, 'outcome.current-deterministic-verification', 'outcome', 'Current main passes 829 deterministic tests', 'CI at main head 1599c42501e5fa7bd8d10c00dc687910b1055b2e passed 122 Vitest files with 817 tests plus 12 Node script tests, along with format, source policy, typecheck, build, and 178 documentation-link checks.', 'completed', '2026-07-28T13:53:00Z', '2026-07-28T13:53:00Z', '{"lifecycle":"active","kind":"verification","arc":"testing","evidence":["CI run:30365511068 head 1599c42501e5fa7bd8d10c00dc687910b1055b2e","workflow:.github/workflows/ci.yml@aee82c9e42e1495fee67347741e143fb29880491"],"views":["overview","testing","current-architecture"],"current":true,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"outcome.current-deterministic-verification"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (41, 'observation.live-discord-remains-credentialed', 'observation', 'Live Discord verification remains credentialed and opt-in', 'smoke:discord and a minimal gateway round trip are needed for REST configuration, intents, gateway delivery, platform permissions, and native rendering; default CI intentionally does not require a token or server.', 'active', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"unresolved","kind":"verification-gap","arc":"testing","evidence":["PR:#27 merged 015aa5062735bf1233b400ee13e453029887c1ec","path:package.json@1835066c7c31ca327384fe217b7bffd960128a21 smoke:discord"],"views":["testing","reliability-risk"],"current":false,"owner_repo":"laurajoyhutchins/discordagent","confidence":"qualified","semantic_id":"observation.live-discord-remains-credentialed"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (42, 'decision.taskcoordinator-direct-runtime', 'decision', 'Use TaskCoordinator as authority for direct provider tasks', 'For the current in-repository direct runtime, TaskCoordinator orders admission, Discord and Git side effects, task/session persistence, provider execution, normalized events, terminal results, continuation, cancellation, and recovery.', 'active', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"active","kind":"decision","arc":"execution-boundary","evidence":["PR:#4 merged df46057dc6dd43e172d1be6cc458101d8d428bbb","path:docs/explanation/architecture/provider-neutral-runtime.md@c36f1324787039df31ec86d63aac44904eebe28b"],"views":["current-architecture","factory-floor","authority-security"],"current":true,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"decision.taskcoordinator-direct-runtime"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (43, 'option.run-all-work-in-bot-process', 'option', 'Keep all future execution authority inside the Discord bot', 'The direct runtime works, but expanding queueing, attempts, artifacts, retries, receipts, streaming, and multi-surface inspection inside a presentation process would duplicate control-plane semantics and bind recovery to Discord availability.', 'superseded', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"superseded","kind":"alternative","arc":"execution-boundary","evidence":["PR:#11 closed unmerged head 3538bfe5444eba47fd106d0f977ef689225269e8","PR:#14 merged d55ef6c8d5efe6ce19b60503766287bd7548a66f"],"views":["factory-floor","reliability-risk"],"current":false,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"option.run-all-work-in-bot-process"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (44, 'action.factory-floor-bridge-attempt', 'action', 'Prototype a direct Factory Floor Discord bridge', 'PR 11 proposed operator API commands, thread/run bindings, status cards, approvals, cancellation, polling, and restart restoration, but it closed unmerged and depended on a worker topology that was not yet ready.', 'rejected', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"abandoned","kind":"prototype","arc":"factory-floor","evidence":["PR:#11 closed unmerged head 3538bfe5444eba47fd106d0f977ef689225269e8"],"views":["factory-floor","overview"],"current":false,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"action.factory-floor-bridge-attempt"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (45, 'revisit.factory-floor-integration-boundary', 'revisit', 'Correct the Factory Floor integration boundary', 'The abandoned bridge was replaced by a sharper ownership model: Discord Agent owns Discord identity, launch context, and projections; Factory Floor owns runtime commands, runs, attempts, artifacts, approvals, cancellation, and canonical queries.', 'completed', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"active","kind":"correction","arc":"factory-floor","evidence":["PR:#14 head d5b830e5994cad9318a8f059d69a37cdfa410c9c merged d55ef6c8d5efe6ce19b60503766287bd7548a66f","path:docs/explanation/architecture/factory-floor-activity-boundary.md@4511942771e23f529d7cfe7400e5bde92829c452"],"views":["overview","factory-floor","current-architecture"],"current":false,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"revisit.factory-floor-integration-boundary"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (46, 'decision.factory-floor-authority', 'decision', 'Keep Factory Floor authoritative for Factory Floor-linked runs', 'Commands, runs, deliveries, executions, attempts, artifacts, lineage, policy decisions, approvals, cancellation, durable runtime state, and operator queries remain in Factory Floor, not Discord Agent SQLite.', 'active', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"active","kind":"cross-repo-decision","arc":"factory-floor","evidence":["PR:#14 merged d55ef6c8d5efe6ce19b60503766287bd7548a66f","path:docs/explanation/architecture/factory-floor-activity-boundary.md@4511942771e23f529d7cfe7400e5bde92829c452","external:factory-floor/docs/explanation/discord-activity-operator-interface.md"],"views":["overview","factory-floor","authority-security","current-architecture"],"current":true,"owner_repo":"laurajoyhutchins/factory-floor","confidence":"confirmed","semantic_id":"decision.factory-floor-authority"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (47, 'decision.discord-agent-activity-adapter', 'decision', 'Limit Discord Agent to Activity launch, identity, and linkage', 'Discord Agent owns Entry Point handling, current Discord identity and roles, trusted launch registration, OAuth exchange, Activity-instance validation, local project/surface/run linkage, and Discord-native projections.', 'active', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"active","kind":"cross-repo-decision","arc":"factory-floor","evidence":["path:docs/explanation/architecture/factory-floor-activity-boundary.md@4511942771e23f529d7cfe7400e5bde92829c452"],"views":["factory-floor","authority-security","current-architecture"],"current":true,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"decision.discord-agent-activity-adapter"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (48, 'action.factory-floor-bindings-client', 'action', 'Add disabled-by-default Factory Floor bindings and clients', 'PR 43 added migration 11, conflict-aware project/surface/run bindings, replay nonces, directional HMAC service authentication, and typed clients without copying runtime state or making startup network calls.', 'completed', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"active","kind":"implementation","arc":"factory-floor","evidence":["PR:#43 head eeda3eccbe3571e0e6b5b697ee759e2784835e46 merged 3ad4a8bad10e8d8c82d571d47c652b0990caac7b"],"views":["factory-floor","testing","current-architecture"],"current":true,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"action.factory-floor-bindings-client"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (49, 'action.activity-trusted-launch', 'action', 'Implement trusted Activity launch registration', 'PR 59 added server-resolved one-time launch state, current role authorization, project/thread binding resolution, and the global PRIMARY_ENTRY_POINT and LAUNCH_ACTIVITY boundary.', 'completed', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"experimental","kind":"implementation","arc":"factory-floor","evidence":["PR:#59 head d51e11d23d902656268cc71ba81b2617723053f1 merged 0e3ab670315689ebe9a55e85bb0ac078a7fc5bb7"],"views":["factory-floor","authority-security","current-architecture"],"current":false,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"action.activity-trusted-launch"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (50, 'action.activity-oauth-bootstrap', 'action', 'Implement Activity OAuth and session bootstrap broker', 'PR 60 added S256 PKCE state, bounded Discord REST calls, live instance and participant validation, current membership and roles, strict no-store HTTP boundaries, and optional lifecycle isolation.', 'completed', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"experimental","kind":"implementation","arc":"factory-floor","evidence":["PR:#60 head f93d9719182a6ea79fe9c6829ed8743ff3710149 merged b0455559ae07c0143b5788b7bc2575cddafbf636"],"views":["factory-floor","authority-security","current-architecture"],"current":false,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"action.activity-oauth-bootstrap"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (51, 'action.activity-principal-revalidation', 'action', 'Implement fresh principal revalidation for sensitive actions', 'PR 62 added reverse service-authenticated approve/cancel revalidation against the current Activity instance, participant, guild membership, roles, adapter binding, run, and action, failing closed on stale or unavailable evidence.', 'completed', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"experimental","kind":"implementation","arc":"factory-floor","evidence":["PR:#62 head e7dd1798aa2cd8ab4d1a5aef4ab319abebcc0d90 merged fe1ca3c5ed7fce39570bd96f041018699c889fbf"],"views":["factory-floor","authority-security","current-architecture"],"current":false,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"action.activity-principal-revalidation"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (52, 'outcome.activity-integration-partial', 'outcome', 'Activity trust scaffolding exists, but the rich operator console is incomplete', 'Discord Agent contains bindings, launch, OAuth/bootstrap, and revalidation code. The complete reusable React operator UI, run inspection, artifacts, streaming, retries, cancellation flows, production acceptance, and migration away from direct bot-owned execution are not established here.', 'active', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"incomplete","kind":"current-state","arc":"factory-floor","evidence":["path:docs/explanation/architecture/factory-floor-activity-boundary.md@4511942771e23f529d7cfe7400e5bde92829c452","external:factory-floor/docs/explanation/discord-activity-operator-interface.md status proposed architecture"],"views":["overview","factory-floor","current-architecture","reliability-risk"],"current":false,"owner_repo":"laurajoyhutchins/discordagent","confidence":"qualified","semantic_id":"outcome.activity-integration-partial"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (53, 'option.activity-replaces-chat', 'option', 'Treat the Discord Activity as a replacement for chat', 'A richer console can show lists, status, artifacts, controls, and topology, but chat remains the conversational surface for initiation, explanation, questions, and lightweight notifications.', 'rejected', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"rejected","kind":"alternative","arc":"factory-floor","evidence":["external:factory-floor/docs/explanation/discord-activity-operator-interface.md","path:docs/explanation/architecture/factory-floor-activity-boundary.md@4511942771e23f529d7cfe7400e5bde92829c452"],"views":["factory-floor","transport-interaction"],"current":false,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"option.activity-replaces-chat"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (54, 'decision.private-guild-role-authorization', 'decision', 'Authorize transport access through configured guild and roles', 'The bot is designed for a private server, validates configuration at startup, and restricts interactions using current Discord role membership and scoped channel/project context.', 'active', '2026-07-14T00:00:00Z', '2026-07-14T00:00:00Z', '{"lifecycle":"active","kind":"security-boundary","arc":"authority-security","evidence":["path:README.md@1835066c7c31ca327384fe217b7bffd960128a21","upstream:NicolaiLolansen/DiscordClaude README.md"],"views":["authority-security","current-architecture"],"current":true,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"decision.private-guild-role-authorization"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (55, 'observation.transport-auth-not-tool-authority', 'observation', 'Discord transport authorization is not tool authority', 'Guild membership, role checks, channel scope, and Activity identity establish who may use the transport. They do not independently grant repository tools, provider capabilities, or Factory Floor mutation authority.', 'active', '2026-07-28T00:00:00Z', '2026-08-03T00:00:00Z', '{"lifecycle":"active","kind":"security-distinction","arc":"authority-security","evidence":["path:docs/explanation/architecture/primary-agent-boundary.md@35392a9504e4b9f590b25140538aaff0e92636d3","path:docs/explanation/architecture/factory-floor-activity-boundary.md@4511942771e23f529d7cfe7400e5bde92829c452"],"views":["authority-security","factory-floor","current-architecture"],"current":true,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"observation.transport-auth-not-tool-authority"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (56, 'action.fresh-principal-revalidation', 'action', 'Revalidate Activity principals before sensitive mutations', 'Approve and cancel requests re-fetch current Discord identity, validate durable project, surface, and run bindings, and fail closed when authority is stale or unavailable.', 'completed', '2026-07-28T00:00:00Z', '2026-08-03T00:00:00Z', '{"lifecycle":"active","kind":"security-control","arc":"authority-security","evidence":["PR:#62 merged fe1ca3c5ed7fce39570bd96f041018699c889fbf","path:docs/explanation/architecture/factory-floor-activity-boundary.md@4511942771e23f529d7cfe7400e5bde92829c452"],"views":["authority-security","factory-floor","current-architecture"],"current":true,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"action.fresh-principal-revalidation"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (57, 'decision.redaction-and-bounded-output', 'decision', 'Centralize redaction and bound Discord-facing output', 'Provider events, errors, tool output, links, mentions, and embeds are normalized through repository-owned presentation and redaction boundaries before they reach Discord.', 'active', '2026-07-28T00:00:00Z', '2026-08-03T00:00:00Z', '{"lifecycle":"active","kind":"security-boundary","arc":"authority-security","evidence":["PR:#4 merged df46057dc6dd43e172d1be6cc458101d8d428bbb","test:src/discord/presentationDelivery.test.ts current main"],"views":["authority-security","transport-interaction","current-architecture"],"current":true,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"decision.redaction-and-bounded-output"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (58, 'observation.untrusted-content-remains-risk', 'observation', 'Untrusted content remains a distinct security risk', 'Role checks, tool isolation, redaction, and principal revalidation do not prove complete resistance to prompt injection, malicious attachments, unsafe links, or quoted-content impersonation.', 'active', '2026-07-28T00:00:00Z', '2026-08-03T00:00:00Z', '{"lifecycle":"unresolved","kind":"security-risk","arc":"authority-security","evidence":["path:docs/explanation/architecture/primary-agent-boundary.md@35392a9504e4b9f590b25140538aaff0e92636d3","path:docs/explanation/architecture/factory-floor-activity-boundary.md@4511942771e23f529d7cfe7400e5bde92829c452"],"views":["authority-security","testing"],"current":false,"owner_repo":"laurajoyhutchins/discordagent","confidence":"qualified","semantic_id":"observation.untrusted-content-remains-risk"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (59, 'decision.public-documentation-boundary', 'decision', 'Publish architecture and operations without publishing secrets', 'Public documentation explains provider, runtime, REPL, Discord, backup, and Activity boundaries while credentials, private guild data, local paths, and deployment secrets remain outside the repository.', 'active', '2026-07-28T00:00:00Z', '2026-08-03T00:00:00Z', '{"lifecycle":"active","kind":"publication-boundary","arc":"public-readiness","evidence":["path:README.md@1835066c7c31ca327384fe217b7bffd960128a21","path:docs/README.md current main"],"views":["authority-security","current-architecture"],"current":true,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"decision.public-documentation-boundary"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (60, 'outcome.public-repository-ready', 'outcome', 'The repository is suitable for public source review', 'Source policy, deterministic CI, documentation checks, explicit configuration, and removal of private runtime material support public repository operation and review.', 'completed', '2026-07-28T00:00:00Z', '2026-08-03T00:00:00Z', '{"lifecycle":"active","kind":"readiness-outcome","arc":"public-readiness","evidence":["CI run:30365511068 head 1599c42501e5fa7bd8d10c00dc687910b1055b2e","path:.github/workflows/ci.yml@aee82c9e42e1495fee67347741e143fb29880491"],"views":["testing","authority-security","current-architecture"],"current":true,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"outcome.public-repository-ready"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (61, 'outcome.public-not-production-ready', 'outcome', 'Public and tested does not mean production-ready', 'Passing deterministic tests and publishing source do not establish hardened hosting, complete live Discord verification, operational SLOs, or production acceptance for the Activity and Factory Floor path.', 'active', '2026-07-28T00:00:00Z', '2026-08-03T00:00:00Z', '{"lifecycle":"unresolved","kind":"readiness-qualification","arc":"public-readiness","evidence":["CI run:30365511068 head 1599c42501e5fa7bd8d10c00dc687910b1055b2e","path:package.json@1835066c7c31ca327384fe217b7bffd960128a21 smoke:discord"],"views":["testing","authority-security"],"current":false,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"outcome.public-not-production-ready"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (62, 'observation.activity-console-incomplete', 'observation', 'Activity trust scaffolding exists before the complete console', 'Trusted launch, OAuth bootstrap, bindings, and revalidation are implemented, while the reusable rich client, full run and artifact experience, streaming, retry, and production acceptance remain incomplete.', 'active', '2026-07-28T00:00:00Z', '2026-08-03T00:00:00Z', '{"lifecycle":"incomplete","kind":"implementation-gap","arc":"activity-readiness","evidence":["PR:#62 merged fe1ca3c5ed7fce39570bd96f041018699c889fbf","path:docs/explanation/architecture/factory-floor-activity-boundary.md@4511942771e23f529d7cfe7400e5bde92829c452"],"views":["factory-floor","current-architecture"],"current":false,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"observation.activity-console-incomplete"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (63, 'action.agent-team-composition-validation', 'action', 'Validate effective Agent Team composition', 'Exact revisions, fail-closed reference validation, and intersection-only effective authority make Agent Team configuration inspectable without granting execution authority by declaration alone.', 'completed', '2026-07-28T00:00:00Z', '2026-08-03T00:00:00Z', '{"lifecycle":"active","kind":"integration-control","arc":"agent-team","evidence":["PR:#73 merged fc6dddef12330baabd8d9d8bf1be7949e64d7af6"],"views":["authority-security","factory-floor","current-architecture"],"current":true,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"action.agent-team-composition-validation"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (64, 'observation.agent-team-composition-not-routing', 'observation', 'Validated team composition does not prove routed execution', 'A valid team bundle establishes declared identities and effective authority bounds. It does not prove that work was scheduled, claimed, executed, or completed through Factory Floor.', 'active', '2026-07-28T00:00:00Z', '2026-08-03T00:00:00Z', '{"lifecycle":"unresolved","kind":"integration-distinction","arc":"agent-team","evidence":["PR:#73 merged fc6dddef12330baabd8d9d8bf1be7949e64d7af6","path:docs/explanation/architecture/factory-floor-activity-boundary.md@4511942771e23f529d7cfe7400e5bde92829c452"],"views":["authority-security","factory-floor"],"current":false,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"observation.agent-team-composition-not-routing"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (65, 'action.mission-lifecycle-projection', 'action', 'Persist mission lifecycle and truthful operator projection', 'Mission transitions require transition-local evidence and expose truthful operator state without allowing stale projection data to imply work that did not occur.', 'completed', '2026-07-28T00:00:00Z', '2026-08-03T00:00:00Z', '{"lifecycle":"active","kind":"projection-control","arc":"mission-projection","evidence":["PR:#76 merged 1599c42501e5fa7bd8d10c00dc687910b1055b2e"],"views":["factory-floor","current-architecture","testing"],"current":true,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"action.mission-lifecycle-projection"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (66, 'observation.mission-projection-not-execution', 'observation', 'Mission projection is not an execution receipt', 'Mission state improves operator truthfulness, but only authoritative runtime attempts, artifacts, and receipts can establish that execution occurred and completed.', 'active', '2026-07-28T00:00:00Z', '2026-08-03T00:00:00Z', '{"lifecycle":"unresolved","kind":"projection-distinction","arc":"mission-projection","evidence":["PR:#76 merged 1599c42501e5fa7bd8d10c00dc687910b1055b2e","path:docs/explanation/architecture/factory-floor-activity-boundary.md@4511942771e23f529d7cfe7400e5bde92829c452"],"views":["factory-floor","testing"],"current":false,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"observation.mission-projection-not-execution"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (67, 'decision.direct-runtime-remains-supported', 'decision', 'Keep the direct provider runtime supported during migration', 'TaskCoordinator, SQLite, guarded worktrees, and direct Claude, Codex, and OpenCode adapters remain current behavior until Factory Floor-linked execution reaches equivalent verified capability.', 'active', '2026-07-28T00:00:00Z', '2026-08-03T00:00:00Z', '{"lifecycle":"active","kind":"compatibility-decision","arc":"execution-migration","evidence":["path:docs/explanation/architecture/provider-neutral-runtime.md@c36f1324787039df31ec86d63aac44904eebe28b","path:docs/explanation/architecture/factory-floor-activity-boundary.md@4511942771e23f529d7cfe7400e5bde92829c452"],"views":["current-architecture","factory-floor"],"current":true,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"decision.direct-runtime-remains-supported"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (68, 'revisit.factory-floor-execution-migration', 'revisit', 'Migrate execution authority only after verified parity', 'The portfolio direction favors Factory Floor as the authoritative execution substrate, but migration must preserve provider behavior, recovery, approvals, cancellation, artifacts, and operator truth before direct execution is retired.', 'pending', '2026-07-28T00:00:00Z', '2026-08-03T00:00:00Z', '{"lifecycle":"proposed","kind":"migration-revisit","arc":"execution-migration","evidence":["path:docs/explanation/architecture/factory-floor-activity-boundary.md@4511942771e23f529d7cfe7400e5bde92829c452","external:laurajoyhutchins/factory-floor execution authority direction"],"views":["factory-floor","current-architecture"],"current":false,"owner_repo":"laurajoyhutchins/discordagent","confidence":"qualified","semantic_id":"revisit.factory-floor-execution-migration"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (69, 'observation.cross-repo-authority-is-scoped', 'observation', 'Cross-repository authority is scoped, not inherited', 'Discord Agent may reference Agent Team definitions and Factory Floor runs, but each repository remains authoritative only for the identities, runtime state, and projections it explicitly owns.', 'active', '2026-07-28T00:00:00Z', '2026-08-03T00:00:00Z', '{"lifecycle":"active","kind":"cross-repo-distinction","arc":"portfolio-boundary","evidence":["path:docs/explanation/architecture/factory-floor-activity-boundary.md@4511942771e23f529d7cfe7400e5bde92829c452","PR:#73 merged fc6dddef12330baabd8d9d8bf1be7949e64d7af6"],"views":["authority-security","factory-floor","current-architecture"],"current":true,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"observation.cross-repo-authority-is-scoped"}');

INSERT INTO decision_nodes (id, change_id, node_type, title, description, status, created_at, updated_at, metadata_json) VALUES (70, 'outcome.federated-authority-model', 'outcome', 'The current architecture is a federated authority model', 'Discord Agent owns conversational transport, direct-runtime compatibility, identity bindings, and operator projections; Agent Team owns durable agent meaning; Factory Floor owns linked execution truth. Integration depends on explicit bindings rather than copied state.', 'active', '2026-07-28T00:00:00Z', '2026-08-03T00:00:00Z', '{"lifecycle":"active","kind":"architecture-outcome","arc":"portfolio-boundary","evidence":["path:docs/explanation/architecture/primary-agent-boundary.md@35392a9504e4b9f590b25140538aaff0e92636d3","path:docs/explanation/architecture/factory-floor-activity-boundary.md@4511942771e23f529d7cfe7400e5bde92829c452","PR:#73 merged fc6dddef12330baabd8d9d8bf1be7949e64d7af6"],"views":["current-architecture","authority-security","factory-floor"],"current":true,"owner_repo":"laurajoyhutchins/discordagent","confidence":"confirmed","semantic_id":"outcome.federated-authority-model"}');
